[features]
seeds = true
skip-lint = false
[programs.devnet]
anchor_nft_staking = "GPxuYM4Y8zpNqJC7YiL97yiaXRoQ1cdHey3c85hRviXP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/arihantbansal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
