[features]
seeds = false
skip-lint = false
[programs.localnet]
counter_anchor = "FwXxUffnGsuem4aZw49uPWhjfz9ZhxjAq6pCia4H5Pnz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/arihantbansal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
