[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_anchor = "4Ru1doMwFsUKQad1qMhr3cSPXipRs1jxyfKgAX15qbzX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/arihantbansal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
